---
# Example coast configuration from:
# https://github.com/osrf/mbzirc/wiki/Running-the-coast-environment
model_name: 'quadrotor_1'
model_type: 'mbzirc_quadrotor'
flight_time: 20
position:
  xyz: [-1500, 2, 4.3]
  rpy: [0, 0, 0]
payload:
  slot0:
    sensor: 'mbzirc_hd_camera'
    rpy: [0, 0, 0]
