---
- model_name: 'usv'
  model_type: 'usv'
  position:
    xyz: [-1462, -16.5, 0.3]
    rpy: [0, 0, 0]
  arm_slot: '0'
  arm: mbzirc_oberon7_arm
  gripper: mbzirc_oberon7_gripper
  payload:
    slot0:
      sensor: 'mbzirc_vga_camera'
      rpy: [0, 0, 0]

- model_name: 'quadrotor_1'
  model_type: 'mbzirc_quadrotor'
  flight_time: 20
  position:
    xyz: [-1500, 2, 4.3]
    rpy: [0, 0, 0]
  payload:
    slot0:
      sensor: 'mbzirc_vga_camera'
      rpy: [0, 0, 0]

- model_name: 'quadrotor_2'
  model_type: 'mbzirc_quadrotor'
  flight_time: 20
  position:
    xyz: [-1500, -2, 4.3]
    rpy: [0, 0, 0]
  payload:
    slot0:
      sensor: 'mbzirc_vga_camera'
      rpy: [0, 0, 0]

