---
- model_name: 'usv'
  model_type: 'usv'
  position:
    xyz: [-1462, -16.5, 0.3]
    rpy: [0, 0, 0]

- model_name: 'quadrotor_1'
  model_type: 'mbzirc_quadrotor'
  flight_time: 20
  position:
    xyz: [-1500, 2, 4.3]
    rpy: [0, 0, 0]

- model_name: 'quadrotor_2'
  model_type: 'mbzirc_quadrotor'
  flight_time: 20
  position:
    xyz: [-1500, -2, 4.3]
    rpy: [0, 0, 0]
