---
model_name: 'usv'
model_type: 'usv'
position:
  xyz: [15, 0, 0.3]
  rpy: [0, 0, 0]
payload:
  slot0:
    sensor: 'mbzirc_vga_camera'
    rpy: [0, 0, 0]
  slot1:
    sensor: 'mbzirc_planar_lidar'
    rpy: [0, 0, 0]
  slot2:
    sensor: 'mbzirc_3d_lidar'
    rpy: [0, 0, 0]
  slot3:
    sensor: 'None'
    rpy: [0, 0, 0]
  slot4:
    sensor: 'mbzirc_hd_camera'
    rpy: [0, 45, 0]
  slot5:
    sensor: 'mbzirc_hd_camera'
    rpy: [0, -45, 0]
  slot6:
    sensor: 'mbzirc_vga_camera'
    rpy: [0, 0, 45]
  slot7:
    sensor: 'mbzirc_vga_camera'
    rpy: [0, 0, -45]
